### ISSUE TITLE
kafka tests are showing Error in I/O

### ISSUE THREAD

**Issue by debasish83** [Verizon/trapezium#1]
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:238)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)
16/10/17 17:43:53 WARN Selector: Error in I/O with localhost/127.0.0.1
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.kafka.common.network.Selector.poll(Selector.java:238)
	at org.apache.kafka.clients.NetworkClient.poll(NetworkClient.java:192)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:191)
	at org.apache.kafka.clients.producer.internals.Sender.run(Sender.java:122)
	at java.lang.Thread.run(Thread.java:745)

**Comment by debasish83** [comment]
I setup travis and build is failing on some localhost bind error...can you take a look ?
https://travis-ci.org/Verizon/trapezium/builds/169162276
/etc/hosts need to be changed on docker instance where travis is running ?

**Comment by rastogipankaj** [comment]
Yes, we need to put 127.0.0.1 localhost <machineName>

Do we have access to this machine?

Thanks,
Pankaj

**Comment by debasish83** [comment]
In .travis.yml you can add code to change docker settings...

language: scala
scala:
  - 2.10.3
jdk:
   - oraclejdk7
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libatlas3gf-base libopenblas-base
before_install we have to do things like cat localhost 127.0.0.1 >> /etc/hosts something like that...push that line in to /etc/hosts

**Comment by VenkateshPoosarla** [comment]
look like kafka producer was looking for a broker not existing in your broker list and Hence the Sender was trying to refresh the metadata continuously. I would recommend a fail safe mechanism for the Sender Thread of Kafka.The data could be persisted to local using Callback and limiting the retry by sender by setting metadata.fetch.timeout.ms=1000ms or lower(default 60000ms)

**Comment by debasish83** [comment]
@VenkateshPoosarla can you push a PR for this ? I still could not get it running...
